--
-- PostgreSQL database dump
--

\restrict h3Gw8bpxNH1KdOOmA1jdMstgvHeDcFeSkmtLqZhP5XQfWiR6gbRJjcMxQutVnR4

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-28 23:04:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16403)
-- Name: categoria_incidencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria_incidencia (
    id_categoria integer NOT NULL,
    nombre_categoria character varying(50) NOT NULL,
    sub_categoria character varying(50) NOT NULL
);


ALTER TABLE public.categoria_incidencia OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16402)
-- Name: categoria_incidencia_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria_incidencia ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_incidencia_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16412)
-- Name: distrito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.distrito (
    id_distrito integer NOT NULL,
    latitud double precision NOT NULL,
    longitud double precision NOT NULL,
    nombre_distrito character varying(50) NOT NULL
);


ALTER TABLE public.distrito OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16411)
-- Name: distrito_id_distrito_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.distrito ALTER COLUMN id_distrito ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.distrito_id_distrito_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16422)
-- Name: incidencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidencia (
    estado boolean NOT NULL,
    fecha_incidencia date NOT NULL,
    id_categoria integer,
    id_distrito integer,
    id_incidencia integer NOT NULL,
    id_usuario integer,
    descripcion character varying(250) NOT NULL
);


ALTER TABLE public.incidencia OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16421)
-- Name: incidencia_id_incidencia_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidencia ALTER COLUMN id_incidencia ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidencia_id_incidencia_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16432)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    password character varying(20) NOT NULL,
    email character varying(50) NOT NULL,
    nombre_usuario character varying(50) NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16431)
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16442)
-- Name: zona_preferida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zona_preferida (
    distrito integer,
    id_usuario integer,
    id_zona integer CONSTRAINT zon_preferida_id_zona_not_null NOT NULL,
    nombre_distrito character varying(50) CONSTRAINT zon_preferida_nombre_distrito_not_null NOT NULL
);


ALTER TABLE public.zona_preferida OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16441)
-- Name: zon_preferida_id_zona_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zona_preferida ALTER COLUMN id_zona ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zon_preferida_id_zona_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5039 (class 0 OID 16403)
-- Dependencies: 220
-- Data for Name: categoria_incidencia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) FROM stdin;
\.


--
-- TOC entry 5041 (class 0 OID 16412)
-- Dependencies: 222
-- Data for Name: distrito; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.distrito (id_distrito, latitud, longitud, nombre_distrito) FROM stdin;
1	0.1124124142	0.11231231	San juan de Lurigancho
\.


--
-- TOC entry 5043 (class 0 OID 16422)
-- Dependencies: 224
-- Data for Name: incidencia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidencia (estado, fecha_incidencia, id_categoria, id_distrito, id_incidencia, id_usuario, descripcion) FROM stdin;
\.


--
-- TOC entry 5045 (class 0 OID 16432)
-- Dependencies: 226
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_usuario, password, email, nombre_usuario) FROM stdin;
\.


--
-- TOC entry 5047 (class 0 OID 16442)
-- Dependencies: 228
-- Data for Name: zona_preferida; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zona_preferida (distrito, id_usuario, id_zona, nombre_distrito) FROM stdin;
\.


--
-- TOC entry 5053 (class 0 OID 0)
-- Dependencies: 219
-- Name: categoria_incidencia_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categoria_incidencia_id_categoria_seq', 1, false);


--
-- TOC entry 5054 (class 0 OID 0)
-- Dependencies: 221
-- Name: distrito_id_distrito_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.distrito_id_distrito_seq', 1, true);


--
-- TOC entry 5055 (class 0 OID 0)
-- Dependencies: 223
-- Name: incidencia_id_incidencia_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidencia_id_incidencia_seq', 1, false);


--
-- TOC entry 5056 (class 0 OID 0)
-- Dependencies: 225
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 1, false);


--
-- TOC entry 5057 (class 0 OID 0)
-- Dependencies: 227
-- Name: zon_preferida_id_zona_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zon_preferida_id_zona_seq', 1, false);


--
-- TOC entry 4877 (class 2606 OID 16410)
-- Name: categoria_incidencia categoria_incidencia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria_incidencia
    ADD CONSTRAINT categoria_incidencia_pkey PRIMARY KEY (id_categoria);


--
-- TOC entry 4879 (class 2606 OID 16420)
-- Name: distrito distrito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.distrito
    ADD CONSTRAINT distrito_pkey PRIMARY KEY (id_distrito);


--
-- TOC entry 4881 (class 2606 OID 16430)
-- Name: incidencia incidencia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidencia
    ADD CONSTRAINT incidencia_pkey PRIMARY KEY (id_incidencia);


--
-- TOC entry 4883 (class 2606 OID 16440)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- TOC entry 4885 (class 2606 OID 16448)
-- Name: zona_preferida zon_preferida_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zona_preferida
    ADD CONSTRAINT zon_preferida_pkey PRIMARY KEY (id_zona);


--
-- TOC entry 4886 (class 2606 OID 16449)
-- Name: incidencia fk6p26ayqtcnume300v7yg4ktjm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidencia
    ADD CONSTRAINT fk6p26ayqtcnume300v7yg4ktjm FOREIGN KEY (id_categoria) REFERENCES public.categoria_incidencia(id_categoria);


--
-- TOC entry 4887 (class 2606 OID 16454)
-- Name: incidencia fkftas2d1cws2m3wnokv0lsi6ek; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidencia
    ADD CONSTRAINT fkftas2d1cws2m3wnokv0lsi6ek FOREIGN KEY (id_distrito) REFERENCES public.distrito(id_distrito);


--
-- TOC entry 4889 (class 2606 OID 16464)
-- Name: zona_preferida fkkrsmt4f0u48a96ufw8jl0fw25; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zona_preferida
    ADD CONSTRAINT fkkrsmt4f0u48a96ufw8jl0fw25 FOREIGN KEY (distrito) REFERENCES public.distrito(id_distrito);


--
-- TOC entry 4890 (class 2606 OID 16469)
-- Name: zona_preferida fkpt65tt0vbbdonnjvw6s6vp5qg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zona_preferida
    ADD CONSTRAINT fkpt65tt0vbbdonnjvw6s6vp5qg FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 4888 (class 2606 OID 16459)
-- Name: incidencia fktejfl7fk3d67l7ho471cftgba; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidencia
    ADD CONSTRAINT fktejfl7fk3d67l7ho471cftgba FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


-- Completed on 2026-04-28 23:04:01

--
-- PostgreSQL database dump complete
--

\unrestrict h3Gw8bpxNH1KdOOmA1jdMstgvHeDcFeSkmtLqZhP5XQfWiR6gbRJjcMxQutVnR4

