--
-- PostgreSQL database dump
--

\restrict h3Gw8bpxNH1KdOOmA1jdMstgvHeDcFeSkmtLqZhP5XQfWiR6gbRJjcMxQutVnR4

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-28 23:04:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16403)
-- Name: categoria_incidencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria_incidencia (
    id_categoria integer NOT NULL,
    nombre_categoria character varying(50) NOT NULL,
    sub_categoria character varying(50) NOT NULL
);


ALTER TABLE public.categoria_incidencia OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16402)
-- Name: categoria_incidencia_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria_incidencia ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_incidencia_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16412)
-- Name: distrito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.distrito (
    id_distrito integer NOT NULL,
    latitud double precision NOT NULL,
    longitud double precision NOT NULL,
    nombre_distrito character varying(50) NOT NULL
);


ALTER TABLE public.distrito OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16411)
-- Name: distrito_id_distrito_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.distrito ALTER COLUMN id_distrito ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.distrito_id_distrito_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16422)
-- Name: incidencia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.incidencia (
    estado boolean NOT NULL,
    fecha_incidencia date NOT NULL,
    id_categoria integer,
    id_distrito integer,
    id_incidencia integer NOT NULL,
    id_usuario integer,
    descripcion character varying(250) NOT NULL
);


ALTER TABLE public.incidencia OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16421)
-- Name: incidencia_id_incidencia_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.incidencia ALTER COLUMN id_incidencia ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidencia_id_incidencia_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16432)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    password character varying(20) NOT NULL,
    email character varying(50) NOT NULL,
    nombre_usuario character varying(50) NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16431)
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16442)
-- Name: zona_preferida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zona_preferida (
    distrito integer,
    id_usuario integer,
    id_zona integer CONSTRAINT zon_preferida_id_zona_not_null NOT NULL,
    nombre_distrito character varying(50) CONSTRAINT zon_preferida_nombre_distrito_not_null NOT NULL
);


ALTER TABLE public.zona_preferida OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16441)
-- Name: zon_preferida_id_zona_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zona_preferida ALTER COLUMN id_zona ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zon_preferida_id_zona_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5039 (class 0 OID 16403)
-- Dependencies: 220
-- Data for Name: categoria_incidencia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) FROM stdin;
\.


--
-- TOC entry 5041 (class 0 OID 16412)
-- Dependencies: 222
-- Data for Name: distrito; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.distrito (id_distrito, latitud, longitud, nombre_distrito) FROM stdin;
1	0.1124124142	0.11231231	San juan de Lurigancho
\.


--
-- TOC entry 5043 (class 0 OID 16422)
-- Dependencies: 224
-- Data for Name: incidencia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.incidencia (estado, fecha_incidencia, id_categoria, id_distrito, id_incidencia, id_usuario, descripcion) FROM stdin;
\.


--
-- TOC entry 5045 (class 0 OID 16432)
-- Dependencies: 226
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_usuario, password, email, nombre_usuario) FROM stdin;
\.


--
-- TOC entry 5047 (class 0 OID 16442)
-- Dependencies: 228
-- Data for Name: zona_preferida; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zona_preferida (distrito, id_usuario, id_zona, nombre_distrito) FROM stdin;
\.


--
-- TOC entry 5053 (class 0 OID 0)
-- Dependencies: 219
-- Name: categoria_incidencia_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categoria_incidencia_id_categoria_seq', 1, false);


--
-- TOC entry 5054 (class 0 OID 0)
-- Dependencies: 221
-- Name: distrito_id_distrito_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.distrito_id_distrito_seq', 1, true);


--
-- TOC entry 5055 (class 0 OID 0)
-- Dependencies: 223
-- Name: incidencia_id_incidencia_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.incidencia_id_incidencia_seq', 1, false);


--
-- TOC entry 5056 (class 0 OID 0)
-- Dependencies: 225
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 1, false);


--
-- TOC entry 5057 (class 0 OID 0)
-- Dependencies: 227
-- Name: zon_preferida_id_zona_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zon_preferida_id_zona_seq', 1, false);


--
-- TOC entry 4877 (class 2606 OID 16410)
-- Name: categoria_incidencia categoria_incidencia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria_incidencia
    ADD CONSTRAINT categoria_incidencia_pkey PRIMARY KEY (id_categoria);


--
-- TOC entry 4879 (class 2606 OID 16420)
-- Name: distrito distrito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.distrito
    ADD CONSTRAINT distrito_pkey PRIMARY KEY (id_distrito);


--
-- TOC entry 4881 (class 2606 OID 16430)
-- Name: incidencia incidencia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidencia
    ADD CONSTRAINT incidencia_pkey PRIMARY KEY (id_incidencia);


--
-- TOC entry 4883 (class 2606 OID 16440)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- TOC entry 4885 (class 2606 OID 16448)
-- Name: zona_preferida zon_preferida_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zona_preferida
    ADD CONSTRAINT zon_preferida_pkey PRIMARY KEY (id_zona);


--
-- TOC entry 4886 (class 2606 OID 16449)
-- Name: incidencia fk6p26ayqtcnume300v7yg4ktjm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidencia
    ADD CONSTRAINT fk6p26ayqtcnume300v7yg4ktjm FOREIGN KEY (id_categoria) REFERENCES public.categoria_incidencia(id_categoria);


--
-- TOC entry 4887 (class 2606 OID 16454)
-- Name: incidencia fkftas2d1cws2m3wnokv0lsi6ek; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidencia
    ADD CONSTRAINT fkftas2d1cws2m3wnokv0lsi6ek FOREIGN KEY (id_distrito) REFERENCES public.distrito(id_distrito);


--
-- TOC entry 4889 (class 2606 OID 16464)
-- Name: zona_preferida fkkrsmt4f0u48a96ufw8jl0fw25; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zona_preferida
    ADD CONSTRAINT fkkrsmt4f0u48a96ufw8jl0fw25 FOREIGN KEY (distrito) REFERENCES public.distrito(id_distrito);


--
-- TOC entry 4890 (class 2606 OID 16469)
-- Name: zona_preferida fkpt65tt0vbbdonnjvw6s6vp5qg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zona_preferida
    ADD CONSTRAINT fkpt65tt0vbbdonnjvw6s6vp5qg FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- TOC entry 4888 (class 2606 OID 16459)
-- Name: incidencia fktejfl7fk3d67l7ho471cftgba; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.incidencia
    ADD CONSTRAINT fktejfl7fk3d67l7ho471cftgba FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


-- Completed on 2026-04-28 23:04:01

--
-- PostgreSQL database dump complete
--

\unrestrict h3Gw8bpxNH1KdOOmA1jdMstgvHeDcFeSkmtLqZhP5XQfWiR6gbRJjcMxQutVnR4

-- ==========================================
-- DATA: categoria_incidencia
-- ==========================================
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (1, 'Infraestructura', 'Bache en pista');
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (2, 'Infraestructura', 'Vereda dañada');
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (3, 'Seguridad', 'Robo a transeúnte');
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (4, 'Seguridad', 'Vandalismo');
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (5, 'Limpieza', 'Acumulación de basura');
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (6, 'Limpieza', 'Desmonte en vía pública');
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (7, 'Alumbrado', 'Poste sin luz');
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (8, 'Alumbrado', 'Cable eléctrico caído');
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (9, 'Tránsito', 'Señal de tránsito dañada');
INSERT INTO public.categoria_incidencia (id_categoria, nombre_categoria, sub_categoria) VALUES (10, 'Tránsito', 'Semáforo en mal estado');

-- ==========================================
-- DATA: distrito
-- ==========================================
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (1, -12.0464, -77.0428, 'Lima Centro');
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (2, -12.1219, -77.0291, 'Miraflores');
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (3, -12.1300, -77.0172, 'San Isidro');
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (4, -12.0874, -77.0472, 'Jesús María');
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (5, -12.0565, -76.9894, 'San Juan de Lurigancho');
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (6, -12.1549, -76.9706, 'La Molina');
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (7, -12.0931, -77.0081, 'San Borja');
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (8, -12.0750, -77.0833, 'Callao');
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (9, -12.1628, -76.9995, 'Santiago de Surco');
INSERT INTO public.distrito (id_distrito, latitud, longitud, nombre_distrito) VALUES (10, -11.9925, -77.0531, 'Comas');

-- ==========================================
-- DATA: usuario
-- ==========================================
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (1, 'pass1234', 'carlos.ramos@gmail.com', 'Carlos Ramos');
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (2, 'pass1234', 'lucia.flores@gmail.com', 'Lucia Flores');
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (3, 'pass1234', 'miguel.torres@gmail.com', 'Miguel Torres');
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (4, 'pass1234', 'ana.garcia@gmail.com', 'Ana Garcia');
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (5, 'pass1234', 'jose.mendoza@gmail.com', 'Jose Mendoza');
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (6, 'pass1234', 'rosa.perez@gmail.com', 'Rosa Perez');
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (7, 'pass1234', 'luis.vargas@gmail.com', 'Luis Vargas');
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (8, 'pass1234', 'maria.quispe@gmail.com', 'Maria Quispe');
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (9, 'pass1234', 'pedro.castillo@gmail.com', 'Pedro Castillo');
INSERT INTO public.usuario (id_usuario, password, email, nombre_usuario) VALUES (10, 'pass1234', 'elena.huanca@gmail.com', 'Elena Huanca');

-- ==========================================
-- DATA: incidencia
-- ==========================================
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (1,  true,  '2026-01-10', 1, 1, 1, 'Bache profundo en la Av. Abancay frente al mercado.');
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (2,  false, '2026-01-15', 3, 2, 2, 'Robo a mano armada en el parque Kennedy.');
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (3,  true,  '2026-01-20', 5, 3, 3, 'Acumulación de basura en la Av. Javier Prado.');
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (4,  false, '2026-02-05', 7, 4, 4, 'Poste de alumbrado sin luz en Jr. Huiracocha.');
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (5,  true,  '2026-02-10', 2, 5, 5, 'Vereda rota frente al colegio en SJL.');
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (6,  false, '2026-02-18', 9, 6, 6, 'Señal de tránsito caída en La Molina.');
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (7,  true,  '2026-03-01', 4, 7, 7, 'Grafitis en la pared del parque San Borja.');
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (8,  false, '2026-03-12', 6, 8, 8, 'Desmonte botado en la Av. Néstor Gambetta.');
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (9,  true,  '2026-03-20', 10, 9, 9, 'Semáforo dañado en la Av. Benavides, Surco.');
INSERT INTO public.incidencia (id_incidencia, estado, fecha_incidencia, id_categoria, id_distrito, id_usuario, descripcion) VALUES (10, false, '2026-04-01', 8, 10, 10, 'Cable eléctrico caído en la Av. Túpac Amaru, Comas.');

-- ==========================================
-- DATA: zona_preferida
-- ==========================================
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (1,  1,  1,  'Lima Centro');
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (2,  2,  2,  'Miraflores');
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (3,  3,  3,  'San Isidro');
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (4,  4,  4,  'Jesús María');
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (5,  5,  5,  'San Juan de Lurigancho');
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (6,  6,  6,  'La Molina');
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (7,  7,  7,  'San Borja');
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (8,  8,  8,  'Callao');
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (9,  9,  9,  'Santiago de Surco');
INSERT INTO public.zona_preferida (id_zona, distrito, id_usuario, nombre_distrito) VALUES (10, 10, 10, 'Comas');
